#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Eventum interface rest server API
  description: Nodejs
  license:
    name: Eventum, 2020-I
host: host:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /imagesByTag/{idTag}:
    get:
      summary: Returns images with the given id tag
      operationId: imagesByTag
      parameters:
        - name: idTag
          in: path
          description: The id of tag
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Myresponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorModel'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    
            
  /getAllTags:
    get:
      summary: Returns all tags
      operationId: getAllTags
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Myresponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'

            
definitions:


  # Group type
  Myresponse:
    type : object
    properties:
      id_type:
        type: integer
      name:
        type: string
  
# Errors
  ErrorModel:
    type: object
    required:
      - message
      - code
    properties:
      code:
        type: number
      name:
        type: string
      description:
        type: string